# Generated by Django 4.2.13 on 2024-06-07 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
    ]
