# Generated by Django 4.2.13 on 2024-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_remove_user_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone_number',
            field=models.CharField(max_length=18, verbose_name='Номер телефона'),
        ),
    ]
