# Generated by Django 4.2.13 on 2024-06-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_birthday_alter_user_telephone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
